# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text=b'\xe5\xa7\x93\xe5\x90\x8d', max_length=30)),
                ('phone', models.CharField(help_text=b'\xe6\x89\x8b\xe6\x9c\xba', max_length=18)),
            ],
            options={
                'db_table': 't_user_permission',
                'verbose_name': '\u7528\u6237\u6743\u9650\u63a7\u5236',
                'verbose_name_plural': '\u7528\u6237\u6743\u9650\u63a7\u5236',
            },
        ),
    ]
