# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_DDLAUDIT_BATCH_DETAIL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sqlnum', models.IntegerField()),
                ('sqltext', models.TextField()),
                ('sqltype', models.CharField(choices=[(b'createtab_select', b'CREATETAB_SELECT'), (b'createtab', b'CREATETAB'), (b'createidx', b'CREATEIDX'), (b'createseq', b'CREATESEQ'), (b'commenttab', b'COMMENTTAB'), (b'commentcol', b'COMMENTCOL'), (b'truncate', b'TRUNCATE'), (b'addpk', b'ADDPK'), (b'adduk', b'ADDUK'), (b'addcol', b'ADDCOL'), (b'renamecol', b'RENAMECOL'), (b'modifycol', b'MODIFYCOL'), (b'dropcol', b'DROPCOL'), (b'dropconst', b'DROPCONST'), (b'droptab', b'DROPTAB'), (b'dropidx', b'DROPIDX'), (b'dropseq', b'DROPSEQ'), (b'othersql', b'OTHERSQL')], max_length=16)),
                ('audit_result', models.TextField(help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe7\xbb\x93\xe6\x9e\x9c')),
                ('audit_status', models.IntegerField(help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe7\xbb\x93\xe6\x9e\x9c\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x9a\xe9\x80\x9a\xe8\xbf\x87\xef\xbc\x8c\xe5\xbe\x85\xe4\xbf\xae\xe6\x94\xb9\xef\xbc\x8c\xe4\xb8\x8d\xe9\x80\x9a\xe8\xbf\x87')),
            ],
            options={
                'db_table': 'T_DDLAUDIT_BATCH_DETAIL',
                'verbose_name': 'DDL\u6279\u6b21\u8be6\u60c5\u8868',
                'verbose_name_plural': 'DDL\u6279\u6b21\u8be6\u60c5\u8868',
            },
        ),
        migrations.CreateModel(
            name='T_DDLAUDIT_BATCH_INFO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_user', models.CharField(help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe6\x8f\x90\xe4\xba\xa4\xe4\xba\xba', max_length=64)),
                ('audit_batch', models.CharField(db_index=True, help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe6\x89\xb9\xe6\xac\xa1\xe5\x8f\xb7', max_length=64)),
                ('audit_time', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.CharField(help_text=b'\xe5\xba\x94\xe7\x94\xa8\xe6\xa8\xa1\xe5\x9d\x97\xe5\x90\x8d', max_length=64)),
                ('db_type', models.CharField(choices=[(b'oracle', b'ORACLE'), (b'mysql', b'MySQL')], help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\xb1\xbb\xe5\x9e\x8b', max_length=32)),
                ('allsqltext', models.TextField(help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe6\x96\x87\xe6\x9c\xac')),
                ('sqlamount', models.IntegerField(help_text=b'\xe6\x89\xb9\xe6\xac\xa1DDL\xe6\x9d\xa1\xe6\x95\xb0')),
                ('batch_status', models.CharField(blank=True, help_text=b'\xe6\x89\xb9\xe6\xac\xa1\xe5\xae\xa1\xe6\xa0\xb8\xe7\x8a\xb6\xe6\x80\x81', max_length=16)),
                ('evaluator', models.CharField(blank=True, help_text=b'review\xe4\xba\xba', max_length=64)),
                ('execute_status', models.CharField(help_text=b'\xe6\x89\xa7\xe8\xa1\x8c\xe7\x8a\xb6\xe6\x80\x81', max_length=8)),
                ('executor', models.CharField(blank=True, help_text=b'\xe6\x89\xa7\xe8\xa1\x8c\xe4\xba\xba', max_length=64)),
                ('exe_failreason', models.CharField(blank=True, help_text=b'\xe6\x89\xa7\xe8\xa1\x8c\xe5\xa4\xb1\xe8\xb4\xa5\xe5\x8e\x9f\xe5\x9b\xa0', max_length=128)),
            ],
            options={
                'db_table': 'T_DDLAUDIT_BATCH_INFO',
                'verbose_name': 'DDL\u6279\u6b21\u4fe1\u606f\u8868',
                'verbose_name_plural': 'DDL\u6279\u6b21\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='t_ddlaudit_batch_detail',
            name='audit_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddlaudit.T_DDLAUDIT_BATCH_INFO'),
        ),
    ]
