# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddlaudit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ddlaudit_batch_info',
            name='release_date',
            field=models.IntegerField(blank=True, default=20134321, help_text=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_ddlaudit_batch_info',
            name='batch_status',
            field=models.CharField(blank=True, help_text=b'\xe6\x89\xb9\xe6\xac\xa1\xe7\x8a\xb6\xe6\x80\x81', max_length=16),
        ),
    ]
