# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddlaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ddlaudit_batch_detail',
            name='audit_status',
            field=models.IntegerField(help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe7\xbb\x93\xe6\x9e\x9c\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x9a\xe9\x80\x9a\xe8\xbf\x87\xef\xbc\x8c\xe8\xad\xa6\xe5\x91\x8a\xef\xbc\x8c\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x8c\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AlterField(
            model_name='t_ddlaudit_batch_info',
            name='evaluator',
            field=models.CharField(blank=True, help_text=b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xba\xba', max_length=64),
        ),
    ]
