# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_CMDB_DBINFO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('db_name', models.CharField(help_text=b'db_type ip port servicename db_usage\xe7\xad\x89\xe7\x9a\x84\xe5\x88\xab\xe7\xa7\xb0 \xe7\xa1\xae\xe5\xae\x9a\xe4\xb8\x80\xe4\xb8\xaa\xe5\xae\x9e\xe4\xbe\x8b', max_length=64)),
                ('db_type', models.CharField(choices=[(b'oracle', b'ORACLE'), (b'mysql', b'MySQL'), (b'redis', b'REDIS')], help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\xb1\xbb\xe5\x9e\x8b', max_length=32)),
                ('ipadress', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=8)),
                ('servicename', models.CharField(blank=True, help_text=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x90\x8d,\xe4\xbb\x85ORACLE\xe9\x9c\x80\xe8\xa6\x81', max_length=32)),
                ('db_usage', models.CharField(choices=[(b'pro', b'\xe7\x94\x9f\xe4\xba\xa7'), (b'dev', b'\xe5\xbc\x80\xe5\x8f\x91'), (b'test', b'\xe6\xb5\x8b\xe8\xaf\x95'), (b'qa', b'\xe5\x8e\x8b\xe6\xb5\x8b')], help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\x8e\xaf\xe5\xa2\x83', max_length=10)),
                ('dbausername', models.CharField(blank=True, help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93DBA\xe7\xbb\xb4\xe6\x8a\xa4\xe8\xb4\xa6\xe6\x88\xb7', max_length=64)),
                ('dbapassword', models.CharField(blank=True, help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93DBA\xe7\xbb\xb4\xe6\x8a\xa4\xe8\xb4\xa6\xe5\x8f\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=64)),
                ('sysuser', models.CharField(help_text=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xb4\xa6\xe5\x8f\xb7', max_length=64)),
                ('syspassword', models.CharField(help_text=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xb4\xa6\xe5\x8f\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=64)),
                ('directory', models.CharField(blank=True, help_text=b'oracle \xe5\xaf\xbc\xe5\x85\xa5\xe5\xaf\xbc\xe5\x87\xba\xe8\xb7\xaf\xe5\xbe\x84', max_length=64)),
                ('skema', models.CharField(help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93schema', max_length=64)),
                ('username', models.CharField(help_text=b'\xe8\xbf\x9e\xe6\x8e\xa5\xe8\xaf\xa5skema\xe7\x9a\x84\xe7\x94\xa8\xe6\x88\xb7', max_length=64)),
                ('password', models.CharField(help_text=b'\xe8\xbf\x9e\xe6\x8e\xa5\xe8\xaf\xa5skema\xe7\x9a\x84\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=64)),
                ('privilege_flag', models.CharField(choices=[(b'n', b'\xe5\x90\xa6'), (b'y', b'\xe6\x98\xaf')], help_text=b'\xe6\x9d\x83\xe9\x99\x90\xe5\x88\x86\xe7\xa6\xbb\xe6\xa0\x87\xe5\xbf\x97', max_length=1)),
                ('appuser', models.CharField(blank=True, help_text=b'\xe5\xba\x94\xe7\x94\xa8\xe7\x94\xa8\xe6\x88\xb7', max_length=64)),
                ('appuser_password', models.CharField(blank=True, help_text=b'\xe5\xba\x94\xe7\x94\xa8\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=64)),
                ('readuser', models.CharField(blank=True, help_text=b'\xe5\x8f\xaa\xe8\xaf\xbb\xe7\x94\xa8\xe6\x88\xb7', max_length=64)),
                ('readuser_password', models.CharField(blank=True, help_text=b'\xe5\x8f\xaa\xe8\xaf\xbb\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=64)),
                ('default_data_tbs', models.CharField(blank=True, help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe8\xa1\xa8\xe7\xa9\xba\xe9\x97\xb4', max_length=64)),
                ('default_ind_tbs', models.CharField(blank=True, help_text=b'\xe7\xb4\xa2\xe5\xbc\x95\xe8\xa1\xa8\xe7\xa9\xba\xe9\x97\xb4', max_length=64)),
                ('app_name', models.CharField(help_text=b'\xe5\xaf\xb9\xe5\xba\x94\xe5\xba\x94\xe7\x94\xa8\xe6\xa8\xa1\xe5\x9d\x97\xe5\x90\x8d', max_length=64)),
                ('remark', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=128)),
            ],
            options={
                'db_table': 'T_CMDB_DBINFO',
                'verbose_name': '\u6570\u636e\u5e93\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u6570\u636e\u5e93\u4fe1\u606f\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='t_cmdb_dbinfo',
            unique_together=set([('db_name', 'skema', 'app_name')]),
        ),
    ]
