# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_cmdb_dbinfo',
            name='default_data_tbs',
            field=models.CharField(blank=True, help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe8\xa1\xa8\xe7\xa9\xba\xe9\x97\xb4', max_length=64),
        ),
        migrations.AddField(
            model_name='t_cmdb_dbinfo',
            name='default_ind_tbs',
            field=models.CharField(blank=True, help_text=b'\xe7\xb4\xa2\xe5\xbc\x95\xe8\xa1\xa8\xe7\xa9\xba\xe9\x97\xb4', max_length=64),
        ),
    ]
