# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(help_text=b'\xe5\x9f\x9f\xe5\x90\x8d', max_length=128)),
                ('db_port', models.IntegerField(help_text=b'\xe5\xae\x9e\xe4\xbe\x8b\xe7\xab\xaf\xe5\x8f\xa3')),
                ('service_name', models.CharField(help_text=b'\xe5\xae\x9e\xe4\xbe\x8b\xe5\x90\x8d', max_length=32)),
                ('admin_ip', models.CharField(help_text=b'\xe7\xae\xa1\xe7\x90\x86\xe7\xbd\x91IP', max_length=16)),
                ('service_ip', models.CharField(help_text=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe7\xbd\x91IP', max_length=16)),
                ('data_ip', models.CharField(help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe7\xbd\x91IP', max_length=16)),
                ('db_desc', models.CharField(help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x8f\x8f\xe8\xbf\xb0', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
