# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_dbmeta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbmeta',
            table='T_DBMETA_INFO',
        ),
    ]
