# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170728_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbmeta',
            options={'verbose_name': '\u6570\u636e\u5e93\u5143\u6570\u636e', 'verbose_name_plural': '\u6570\u636e\u5e93\u5143\u6570\u636e\u8868'},
        ),
        migrations.AddField(
            model_name='dbmeta',
            name='data_port',
            field=models.IntegerField(default=1540, help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe7\xbd\x91\xe7\xab\xaf\xe5\x8f\xa3'),
        ),
        migrations.AddField(
            model_name='dbmeta',
            name='rw_flag',
            field=models.CharField(default=b'r', help_text=b'\xe8\xaf\xbb\xe5\x86\x99\xe5\xba\x93\xe6\xa0\x87\xe7\xa4\xba\xef\xbc\x8cr\xe8\xaf\xbb\xe5\xba\x93\xef\xbc\x8cw\xe5\x86\x99\xe5\xba\x93', max_length=1),
        ),
    ]
