planchange_dict={'CHANGE_RATE':2,
                  'EXECUTIONS':5,
                  'AVG_TIME_MS':2
                 }

planchange_checksql='''
WITH TMP_TAB AS
 (SELECT INST_ID,
         SQL_ID,
         SQL_FULLTEXT,
         PLAN_HASH_VALUE,
         FIRST_LOAD_TIME,
         LAST_ACTIVE_TIME,
         FIRST_VALUE(LAST_ACTIVE_TIME) OVER(PARTITION BY INST_ID, SQL_ID ORDER BY LAST_ACTIVE_TIME DESC) MAX_LAST_ACTIVE_TIME,
         EXECUTIONS,
         AVG_TIME_MS,
         FIRST_VALUE(AVG_TIME_MS) OVER(PARTITION BY INST_ID, SQL_ID ORDER BY AVG_TIME_MS) BEST_AVG_TIME_MS,
         CEIL(AVG_TIME_MS / FIRST_VALUE(AVG_TIME_MS)
              OVER(PARTITION BY INST_ID, SQL_ID ORDER BY AVG_TIME_MS)) CHANGE_RATE
    FROM (SELECT INST_ID,
                 SQL_ID,
                 SQL_FULLTEXT,
                 PLAN_HASH_VALUE,
                 MIN(FIRST_LOAD_TIME) FIRST_LOAD_TIME,
                 MAX(LAST_ACTIVE_TIME) LAST_ACTIVE_TIME,
                 SUM(EXECUTIONS) EXECUTIONS,
                 ROUND((SUM(ELAPSED_TIME) / SUM(EXECUTIONS) / 1000), 2) AVG_TIME_MS
            FROM GV$SQL
           WHERE EXECUTIONS <> 0
             AND PARSING_SCHEMA_NAME ='{0}'
           GROUP BY INST_ID, SQL_ID, SQL_FULLTEXT, PLAN_HASH_VALUE))
SELECT A.*
  FROM TMP_TAB A,
       (SELECT SQL_ID, INST_ID
          FROM TMP_TAB
         WHERE 
           CHANGE_RATE >= {1} AND
           EXECUTIONS >= {2} AND
           AVG_TIME_MS >= {3} AND
           MAX_LAST_ACTIVE_TIME = LAST_ACTIVE_TIME) B
 WHERE A.SQL_ID = B.SQL_ID
   AND A.INST_ID = B.INST_ID
 ORDER BY A.SQL_ID, A.INST_ID
'''


inefficient_dict={'EXECUTIONS':5,
             'EXE_MIN_SINCE':20,
             'AVG_TIME_MS':5,
             'AVG_GETS_MB':50,
             'AVG_READS_MB':10
            }

inefficient_checksql='''
SELECT 
INST_ID,
SQL_ID,
SQL_FULLTEXT,
PLAN_HASH_VALUE,
FIRST_LOAD_TIME,
TO_CHAR(LAST_ACTIVE_TIME,'YYYY-MM-DD HH24:MI:SS') LAST_ACTIVE_TIME,
EXECUTIONS, 
AVG_TIME_MS,
AVG_GETS_MB,
AVG_READS_MB
FROM (
SELECT    
INST_ID,
SQL_ID,
SQL_FULLTEXT,
PLAN_HASH_VALUE,
FIRST_LOAD_TIME,
LAST_ACTIVE_TIME,
EXECUTIONS,
ROUND((ELAPSED_TIME / EXECUTIONS /1000 )) AVG_TIME_MS,
ROUND((BUFFER_GETS * 8/EXECUTIONS/1024 )) AVG_GETS_MB,
ROUND((PHYSICAL_READ_BYTES / EXECUTIONS/1024/1024 )) AVG_READS_MB
FROM GV$SQLAREA
WHERE PARSING_SCHEMA_NAME='{0}' AND   EXECUTIONS >= 1 )
WHERE 
EXECUTIONS >= {1} AND 
LAST_ACTIVE_TIME > SYSDATE - {2}/1440  AND  
(
AVG_TIME_MS>={3} OR   
AVG_GETS_MB>={4} OR 
AVG_READS_MB>={5} 
) ORDER BY 2,1
'''