# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InefficientSql',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skema', models.CharField(help_text=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93schema', max_length=30)),
                ('inst_id', models.IntegerField(help_text=b'\xe5\xae\x9e\xe4\xbe\x8b\xe5\x8f\xb7')),
                ('sql_id', models.CharField(help_text=b'sql_id', max_length=13)),
                ('sql_text', models.TextField(help_text=b'sql\xe6\x96\x87\xe6\x9c\xac')),
                ('plan_hash_value', models.BigIntegerField(help_text=b'sql\xe7\x9a\x84\xe6\x89\xa7\xe8\xa1\x8c\xe8\xae\xa1\xe5\x88\x92\xe7\xbc\x96\xe5\x8f\xb7')),
                ('first_load_time', models.CharField(help_text=b'\xe7\x88\xb6\xe6\xb8\xb8\xe6\xa0\x87\xe4\xba\xa7\xe7\x94\x9f\xe6\x97\xb6\xe9\x97\xb4', max_length=19)),
                ('last_active_time', models.CharField(help_text=b'\xe6\x9f\x90\xe5\xad\x90\xe6\xb8\xb8\xe6\xa0\x87\xe4\xb8\x8a\xe6\xac\xa1\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4', max_length=19)),
                ('executions', models.IntegerField(help_text=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\xac\xa1\xe6\x95\xb0')),
                ('avg_time_ms', models.IntegerField(help_text=b'\xe5\x8d\x95\xe6\xac\xa1\xe6\x89\xa7\xe8\xa1\x8c\xe5\xb9\xb3\xe5\x9d\x87\xe6\x97\xb6\xe9\x97\xb4')),
                ('avg_gets_mb', models.IntegerField(help_text=b'\xe5\x8d\x95\xe6\xac\xa1\xe6\x89\xa7\xe8\xa1\x8c\xe5\xb9\xb3\xe5\x9d\x87\xe9\x80\xbb\xe8\xbe\x91\xe8\xaf\xbb')),
                ('avg_reads_mb', models.IntegerField(help_text=b'\xe5\x8d\x95\xe6\xac\xa1\xe6\x89\xa7\xe8\xa1\x8c\xe5\xb9\xb3\xe5\x9d\x87\xe7\x89\xa9\xe7\x90\x86\xe8\xaf\xbb')),
                ('status', models.CharField(default=b'init', help_text=b'\xe8\xaf\xad\xe5\x8f\xa5\xe5\xae\xa1\xe6\xa0\xb8\xe7\x8a\xb6\xe6\x80\x81', max_length=10)),
            ],
            options={
                'db_table': 't_sqlstat_inefficientsql',
                'verbose_name': '\u4f4e\u6548sql\u4fe1\u606f',
                'verbose_name_plural': '\u4f4e\u6548sql\u4fe1\u606f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inefficientsql',
            unique_together=set([('skema', 'inst_id', 'sql_id')]),
        ),
    ]
