# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exe_group',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exe_groupname', models.CharField(max_length=128, unique=True)),
                ('group_var', models.CharField(blank=True, max_length=256)),
                ('detail', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'T_NEWBEE_EXEGROUP',
            },
        ),
        migrations.CreateModel(
            name='Exeuser',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('sudo_password', models.CharField(blank=True, max_length=256)),
                ('exe_port', models.IntegerField()),
            ],
            options={
                'db_table': 'T_NEWBEE_EXEUSER',
            },
        ),
        migrations.CreateModel(
            name='Functiongroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fun_groupname', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'T_NEWBEE_FUNCGROUP',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('port', models.IntegerField()),
                ('status', models.IntegerField()),
                ('host_var', models.CharField(max_length=512)),
                ('function_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbee.Functiongroup')),
            ],
            options={
                'db_table': 'T_NEWBEE_HOST',
            },
        ),
        migrations.CreateModel(
            name='Host_exe_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exe_groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbee.Exe_group')),
                ('hostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newbee.Host')),
            ],
            options={
                'db_table': 'T_HOST_EXEGROUP',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=128)),
                ('exe_groupname', models.CharField(max_length=128)),
                ('exe', models.CharField(max_length=128)),
                ('log', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'T_NEWBEE_MISSION',
            },
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'T_NEWBEE_NUM',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=128, unique=True)),
                ('role_var', models.CharField(blank=True, max_length=1024)),
                ('detail', models.CharField(max_length=1024)),
                ('stepnum', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'T_NEWBEE_ROLE',
            },
        ),
    ]
