# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncRecord',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'T_FUNC_RECORD',
            },
        ),
    ]
