# -*- coding:utf-8 -*-
"""
Django settings for dbenvmanager project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

#使用了django自带的broker来作为celery的broker 消息队列  还可以使用redis rabbitmq
BROKER_URL = 'django://localhost:8000//' 


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uhjzjw!_+3xc-s(7861$!8in3$j)s3w-ql$zfy*^(jxib0lh_v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
#DEBUG=False
#ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usercontrol',
    'common',
    'cmdb',
    'dmlaudit',
    'ddlaudit',
    'performance',
    'datatransfer',
    'runanalysis',
    'djcelery',#必须使用
    'kombu.transport.django',#kombu.transport.django是基于Django的broker
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dbenvmanager.urls'



WSGI_APPLICATION = 'dbenvmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

#不用默认的sqllite数据库  用mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dbenvmanager',
        'USER': 'rootbp',
        'PASSWORD': 'root',
        'HOST': '192.168.136.88',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

#USE_TZ = True
#TIME_ZONE = 'UTC'

USE_TZ = False
TIME_ZONE ='Asia/Shanghai'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'



#模板路径

TEMPLATES = [
    {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates')] #html模板路径
                                                      ,
            'APP_DIRS': True,
            'OPTIONS': {
                        'context_processors': [
                                        'django.template.context_processors.debug',
                                        'django.template.context_processors.request', #request.path
                                        'django.contrib.auth.context_processors.auth',#request.user.username
                                        'django.contrib.messages.context_processors.messages',
                                    ],
                    },
        },
 ]


#静态文件路径
STATICFILES_DIRS = (
    os.path.join(os.path.dirname(__file__), '..', 'static').replace('\\', '/'),
)
