# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_datatransfer_expdp',
            name='parallel',
            field=models.CharField(blank=True, help_text=b'\xe5\xb9\xb6\xe8\xa1\x8c\xe5\xba\xa6', max_length=16),
        ),
    ]
